// Code generated by protoc-gen-go. DO NOT EDIT.
// source: videoService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
//Feed
type VideoFeedRequest struct {
	// @inject_tag: json:"latest_time"
	LatestTime int64 `protobuf:"varint,1,opt,name=LatestTime,proto3" json:"LatestTime,omitempty"`
	// @inject_tag: json:"token"
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoFeedRequest) Reset()         { *m = VideoFeedRequest{} }
func (m *VideoFeedRequest) String() string { return proto.CompactTextString(m) }
func (*VideoFeedRequest) ProtoMessage()    {}
func (*VideoFeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{0}
}

func (m *VideoFeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFeedRequest.Unmarshal(m, b)
}
func (m *VideoFeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFeedRequest.Marshal(b, m, deterministic)
}
func (m *VideoFeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFeedRequest.Merge(m, src)
}
func (m *VideoFeedRequest) XXX_Size() int {
	return xxx_messageInfo_VideoFeedRequest.Size(m)
}
func (m *VideoFeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFeedRequest proto.InternalMessageInfo

func (m *VideoFeedRequest) GetLatestTime() int64 {
	if m != nil {
		return m.LatestTime
	}
	return 0
}

func (m *VideoFeedRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VideoFeedResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	// @inject_tag: json:"status_msg"
	StatusMsg string `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	// @inject_tag: json:"video_list"
	VideoList []*Video `protobuf:"bytes,3,rep,name=VideoList,proto3" json:"VideoList,omitempty"`
	// @inject_tag: json:"next_time"
	NextTime             int64    `protobuf:"varint,4,opt,name=NextTime,proto3" json:"NextTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoFeedResponse) Reset()         { *m = VideoFeedResponse{} }
func (m *VideoFeedResponse) String() string { return proto.CompactTextString(m) }
func (*VideoFeedResponse) ProtoMessage()    {}
func (*VideoFeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{1}
}

func (m *VideoFeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFeedResponse.Unmarshal(m, b)
}
func (m *VideoFeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFeedResponse.Marshal(b, m, deterministic)
}
func (m *VideoFeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFeedResponse.Merge(m, src)
}
func (m *VideoFeedResponse) XXX_Size() int {
	return xxx_messageInfo_VideoFeedResponse.Size(m)
}
func (m *VideoFeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFeedResponse proto.InternalMessageInfo

func (m *VideoFeedResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *VideoFeedResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *VideoFeedResponse) GetVideoList() []*Video {
	if m != nil {
		return m.VideoList
	}
	return nil
}

func (m *VideoFeedResponse) GetNextTime() int64 {
	if m != nil {
		return m.NextTime
	}
	return 0
}

//
//PublishAction
type VideoPublishActionRequest struct {
	// @inject_tag: json:"token"
	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	// @inject_tag: json:"data"
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	// @inject_tag: json:"title"
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoPublishActionRequest) Reset()         { *m = VideoPublishActionRequest{} }
func (m *VideoPublishActionRequest) String() string { return proto.CompactTextString(m) }
func (*VideoPublishActionRequest) ProtoMessage()    {}
func (*VideoPublishActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{2}
}

func (m *VideoPublishActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoPublishActionRequest.Unmarshal(m, b)
}
func (m *VideoPublishActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoPublishActionRequest.Marshal(b, m, deterministic)
}
func (m *VideoPublishActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoPublishActionRequest.Merge(m, src)
}
func (m *VideoPublishActionRequest) XXX_Size() int {
	return xxx_messageInfo_VideoPublishActionRequest.Size(m)
}
func (m *VideoPublishActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoPublishActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VideoPublishActionRequest proto.InternalMessageInfo

func (m *VideoPublishActionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VideoPublishActionRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *VideoPublishActionRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type VideoPublishActionResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	// @inject_tag: json:"status_msg"
	StatusMsg            string   `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoPublishActionResponse) Reset()         { *m = VideoPublishActionResponse{} }
func (m *VideoPublishActionResponse) String() string { return proto.CompactTextString(m) }
func (*VideoPublishActionResponse) ProtoMessage()    {}
func (*VideoPublishActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{3}
}

func (m *VideoPublishActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoPublishActionResponse.Unmarshal(m, b)
}
func (m *VideoPublishActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoPublishActionResponse.Marshal(b, m, deterministic)
}
func (m *VideoPublishActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoPublishActionResponse.Merge(m, src)
}
func (m *VideoPublishActionResponse) XXX_Size() int {
	return xxx_messageInfo_VideoPublishActionResponse.Size(m)
}
func (m *VideoPublishActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoPublishActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VideoPublishActionResponse proto.InternalMessageInfo

func (m *VideoPublishActionResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *VideoPublishActionResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

//
//PublishList
type VideoPublishListRequest struct {
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"token"
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoPublishListRequest) Reset()         { *m = VideoPublishListRequest{} }
func (m *VideoPublishListRequest) String() string { return proto.CompactTextString(m) }
func (*VideoPublishListRequest) ProtoMessage()    {}
func (*VideoPublishListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{4}
}

func (m *VideoPublishListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoPublishListRequest.Unmarshal(m, b)
}
func (m *VideoPublishListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoPublishListRequest.Marshal(b, m, deterministic)
}
func (m *VideoPublishListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoPublishListRequest.Merge(m, src)
}
func (m *VideoPublishListRequest) XXX_Size() int {
	return xxx_messageInfo_VideoPublishListRequest.Size(m)
}
func (m *VideoPublishListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoPublishListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VideoPublishListRequest proto.InternalMessageInfo

func (m *VideoPublishListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VideoPublishListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VideoPublishListResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	// @inject_tag: json:"status_msg"
	StatusMsg string `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	// @inject_tag: json:"video_list"
	VideoList            []*Video `protobuf:"bytes,3,rep,name=VideoList,proto3" json:"VideoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoPublishListResponse) Reset()         { *m = VideoPublishListResponse{} }
func (m *VideoPublishListResponse) String() string { return proto.CompactTextString(m) }
func (*VideoPublishListResponse) ProtoMessage()    {}
func (*VideoPublishListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{5}
}

func (m *VideoPublishListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoPublishListResponse.Unmarshal(m, b)
}
func (m *VideoPublishListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoPublishListResponse.Marshal(b, m, deterministic)
}
func (m *VideoPublishListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoPublishListResponse.Merge(m, src)
}
func (m *VideoPublishListResponse) XXX_Size() int {
	return xxx_messageInfo_VideoPublishListResponse.Size(m)
}
func (m *VideoPublishListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoPublishListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VideoPublishListResponse proto.InternalMessageInfo

func (m *VideoPublishListResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *VideoPublishListResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *VideoPublishListResponse) GetVideoList() []*Video {
	if m != nil {
		return m.VideoList
	}
	return nil
}

//
//FavoriteAction
type VideoFavoriteActionRequest struct {
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"token"
	Token string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	// @inject_tag: json:"video_id"
	VideoId int64 `protobuf:"varint,3,opt,name=VideoId,proto3" json:"VideoId,omitempty"`
	// @inject_tag: json:"action_type"
	ActionType           int32    `protobuf:"varint,4,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoFavoriteActionRequest) Reset()         { *m = VideoFavoriteActionRequest{} }
func (m *VideoFavoriteActionRequest) String() string { return proto.CompactTextString(m) }
func (*VideoFavoriteActionRequest) ProtoMessage()    {}
func (*VideoFavoriteActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{6}
}

func (m *VideoFavoriteActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFavoriteActionRequest.Unmarshal(m, b)
}
func (m *VideoFavoriteActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFavoriteActionRequest.Marshal(b, m, deterministic)
}
func (m *VideoFavoriteActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFavoriteActionRequest.Merge(m, src)
}
func (m *VideoFavoriteActionRequest) XXX_Size() int {
	return xxx_messageInfo_VideoFavoriteActionRequest.Size(m)
}
func (m *VideoFavoriteActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFavoriteActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFavoriteActionRequest proto.InternalMessageInfo

func (m *VideoFavoriteActionRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VideoFavoriteActionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VideoFavoriteActionRequest) GetVideoId() int64 {
	if m != nil {
		return m.VideoId
	}
	return 0
}

func (m *VideoFavoriteActionRequest) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type VideoFavoriteActionResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	// @inject_tag: json:"status_msg"
	StatusMsg            string   `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoFavoriteActionResponse) Reset()         { *m = VideoFavoriteActionResponse{} }
func (m *VideoFavoriteActionResponse) String() string { return proto.CompactTextString(m) }
func (*VideoFavoriteActionResponse) ProtoMessage()    {}
func (*VideoFavoriteActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{7}
}

func (m *VideoFavoriteActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFavoriteActionResponse.Unmarshal(m, b)
}
func (m *VideoFavoriteActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFavoriteActionResponse.Marshal(b, m, deterministic)
}
func (m *VideoFavoriteActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFavoriteActionResponse.Merge(m, src)
}
func (m *VideoFavoriteActionResponse) XXX_Size() int {
	return xxx_messageInfo_VideoFavoriteActionResponse.Size(m)
}
func (m *VideoFavoriteActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFavoriteActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFavoriteActionResponse proto.InternalMessageInfo

func (m *VideoFavoriteActionResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *VideoFavoriteActionResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

//
//FavoriteList
type VideoFavoriteListRequest struct {
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// @inject_tag: json:"token"
	Token                string   `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoFavoriteListRequest) Reset()         { *m = VideoFavoriteListRequest{} }
func (m *VideoFavoriteListRequest) String() string { return proto.CompactTextString(m) }
func (*VideoFavoriteListRequest) ProtoMessage()    {}
func (*VideoFavoriteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{8}
}

func (m *VideoFavoriteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFavoriteListRequest.Unmarshal(m, b)
}
func (m *VideoFavoriteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFavoriteListRequest.Marshal(b, m, deterministic)
}
func (m *VideoFavoriteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFavoriteListRequest.Merge(m, src)
}
func (m *VideoFavoriteListRequest) XXX_Size() int {
	return xxx_messageInfo_VideoFavoriteListRequest.Size(m)
}
func (m *VideoFavoriteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFavoriteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFavoriteListRequest proto.InternalMessageInfo

func (m *VideoFavoriteListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VideoFavoriteListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VideoFavoriteListResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"`
	// @inject_tag: json:"status_msg"
	StatusMsg string `protobuf:"bytes,2,opt,name=StatusMsg,proto3" json:"StatusMsg,omitempty"`
	// @inject_tag: json:"video_list"
	VideoList            []*Video `protobuf:"bytes,3,rep,name=VideoList,proto3" json:"VideoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoFavoriteListResponse) Reset()         { *m = VideoFavoriteListResponse{} }
func (m *VideoFavoriteListResponse) String() string { return proto.CompactTextString(m) }
func (*VideoFavoriteListResponse) ProtoMessage()    {}
func (*VideoFavoriteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4ee3c3e3f13865b, []int{9}
}

func (m *VideoFavoriteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoFavoriteListResponse.Unmarshal(m, b)
}
func (m *VideoFavoriteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoFavoriteListResponse.Marshal(b, m, deterministic)
}
func (m *VideoFavoriteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoFavoriteListResponse.Merge(m, src)
}
func (m *VideoFavoriteListResponse) XXX_Size() int {
	return xxx_messageInfo_VideoFavoriteListResponse.Size(m)
}
func (m *VideoFavoriteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoFavoriteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VideoFavoriteListResponse proto.InternalMessageInfo

func (m *VideoFavoriteListResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *VideoFavoriteListResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *VideoFavoriteListResponse) GetVideoList() []*Video {
	if m != nil {
		return m.VideoList
	}
	return nil
}

func init() {
	proto.RegisterType((*VideoFeedRequest)(nil), "services.VideoFeedRequest")
	proto.RegisterType((*VideoFeedResponse)(nil), "services.VideoFeedResponse")
	proto.RegisterType((*VideoPublishActionRequest)(nil), "services.VideoPublishActionRequest")
	proto.RegisterType((*VideoPublishActionResponse)(nil), "services.VideoPublishActionResponse")
	proto.RegisterType((*VideoPublishListRequest)(nil), "services.VideoPublishListRequest")
	proto.RegisterType((*VideoPublishListResponse)(nil), "services.VideoPublishListResponse")
	proto.RegisterType((*VideoFavoriteActionRequest)(nil), "services.VideoFavoriteActionRequest")
	proto.RegisterType((*VideoFavoriteActionResponse)(nil), "services.VideoFavoriteActionResponse")
	proto.RegisterType((*VideoFavoriteListRequest)(nil), "services.VideoFavoriteListRequest")
	proto.RegisterType((*VideoFavoriteListResponse)(nil), "services.VideoFavoriteListResponse")
}

func init() { proto.RegisterFile("videoService.proto", fileDescriptor_c4ee3c3e3f13865b) }

var fileDescriptor_c4ee3c3e3f13865b = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0x65, 0x36, 0x29, 0xcd, 0x24, 0x7c, 0x74, 0x84, 0x60, 0x71, 0x11, 0x0a, 0x2e, 0x48,
	0xb9, 0x10, 0xa4, 0x72, 0xe4, 0x80, 0xf8, 0x50, 0x69, 0xa5, 0x16, 0x21, 0x37, 0x14, 0x29, 0x15,
	0x87, 0x6d, 0x77, 0x04, 0x16, 0x21, 0x0e, 0xb1, 0x13, 0xc1, 0x1d, 0x09, 0x1e, 0x82, 0x17, 0xe1,
	0xed, 0xd0, 0xda, 0xde, 0xd6, 0x09, 0xdb, 0x20, 0xaa, 0x4a, 0x39, 0xed, 0xce, 0xf8, 0xef, 0x9f,
	0x66, 0xfc, 0x1f, 0x1b, 0x70, 0xaa, 0x72, 0xd2, 0xfb, 0x34, 0x9e, 0xaa, 0x63, 0xea, 0x8e, 0xc6,
	0xda, 0x6a, 0x5c, 0x35, 0x3e, 0x34, 0x7c, 0xcd, 0xad, 0xee, 0xe9, 0x9c, 0x06, 0xc6, 0x2f, 0x8a,
	0x6d, 0xb8, 0x7e, 0x50, 0x24, 0xb7, 0x88, 0x72, 0x49, 0x5f, 0x26, 0x64, 0x2c, 0xde, 0x05, 0xd8,
	0xcd, 0x2c, 0x19, 0xdb, 0x53, 0x9f, 0x29, 0x65, 0x6d, 0xd6, 0x49, 0x64, 0x94, 0xc1, 0x1b, 0x50,
	0xef, 0xe9, 0x4f, 0x34, 0x4c, 0x2f, 0xb5, 0x59, 0xa7, 0x21, 0x7d, 0x20, 0x7e, 0x31, 0x58, 0x8b,
	0x50, 0x66, 0xa4, 0x87, 0x86, 0x0a, 0xd6, 0xbe, 0xcd, 0xec, 0xc4, 0xbc, 0xd0, 0xb9, 0x67, 0xd5,
	0x65, 0x94, 0xc1, 0x3b, 0xd0, 0xf0, 0xd1, 0x9e, 0xf9, 0x10, 0x78, 0xa7, 0x09, 0x7c, 0x08, 0x0d,
	0x87, 0xdc, 0x55, 0xc6, 0xa6, 0x49, 0x3b, 0xe9, 0x34, 0x37, 0xaf, 0x75, 0xcb, 0x76, 0xba, 0x6e,
	0x49, 0x9e, 0x2a, 0x90, 0xc3, 0xea, 0x6b, 0xfa, 0xea, 0xcb, 0xae, 0xb9, 0xb2, 0x4f, 0x62, 0x71,
	0x08, 0xb7, 0x9d, 0xf0, 0xcd, 0xe4, 0x68, 0xa0, 0xcc, 0xc7, 0x67, 0xc7, 0x56, 0xe9, 0x61, 0xd9,
	0xf1, 0x49, 0x47, 0x2c, 0xea, 0x08, 0x11, 0x6a, 0x2f, 0x33, 0x9b, 0xb9, 0xb2, 0x5a, 0xd2, 0xfd,
	0x3b, 0xa5, 0xb2, 0x03, 0x4a, 0x93, 0xa0, 0x2c, 0x02, 0xd1, 0x07, 0x5e, 0x05, 0xbf, 0x88, 0x33,
	0x10, 0xaf, 0xe0, 0x56, 0xcc, 0x2e, 0x1a, 0x2d, 0xcb, 0xbe, 0x09, 0x2b, 0x6f, 0x0d, 0x8d, 0x77,
	0xf2, 0x60, 0x52, 0x88, 0xce, 0x30, 0xe8, 0x07, 0x83, 0xf4, 0x6f, 0xd2, 0x12, 0x7c, 0x12, 0xdf,
	0x59, 0x38, 0xaf, 0xad, 0x6c, 0xaa, 0xc7, 0xca, 0xd2, 0xac, 0x1b, 0xff, 0xd5, 0x16, 0xa6, 0x70,
	0xd9, 0xb1, 0x76, 0x72, 0xe7, 0x49, 0x22, 0xcb, 0xb0, 0xe8, 0xc9, 0x83, 0x7b, 0xdf, 0x46, 0x7e,
	0x20, 0xea, 0x32, 0xca, 0x88, 0x43, 0x58, 0xaf, 0xac, 0xe2, 0x42, 0x6c, 0xdb, 0x0e, 0x87, 0x5d,
	0xc2, 0xcf, 0xef, 0xdb, 0x4f, 0x16, 0x46, 0x77, 0x16, 0xb5, 0x04, 0xe3, 0x36, 0x7f, 0x27, 0xd0,
	0x3a, 0x88, 0x5e, 0x18, 0x7c, 0x0a, 0xb5, 0xe2, 0xba, 0x23, 0x9f, 0xdb, 0x14, 0x3d, 0x27, 0x7c,
	0xbd, 0x72, 0x2d, 0x94, 0xdf, 0x87, 0x2b, 0x33, 0x97, 0x06, 0x37, 0xe6, 0xd4, 0x55, 0xf7, 0x95,
	0xdf, 0x5f, 0x2c, 0x0a, 0xec, 0x1e, 0x34, 0xa3, 0x51, 0xc7, 0x7b, 0xd5, 0x9b, 0x22, 0x63, 0xb8,
	0x58, 0x24, 0x09, 0xd4, 0xf7, 0x70, 0x75, 0x76, 0x60, 0x70, 0xbe, 0x9a, 0xca, 0xa9, 0xe6, 0x0f,
	0xfe, 0xa1, 0x0a, 0xf8, 0x77, 0xd0, 0x8a, 0x7d, 0x46, 0x71, 0xc6, 0xb6, 0xb8, 0xec, 0x8d, 0x85,
	0x1a, 0x0f, 0x7e, 0xde, 0xec, 0x37, 0xba, 0x8f, 0x9e, 0xb8, 0x57, 0xdf, 0x1c, 0xad, 0xb8, 0xef,
	0xe3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xfe, 0xaf, 0xc9, 0x30, 0x06, 0x00, 0x00,
}
