// Code generated by protoc-gen-go. DO NOT EDIT.
// source: videoModels.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Video struct {
	// @inject_tag: json:"id"
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// @inject_tag: json:"author"
	Author *User `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	// @inject_tag: json:"play_url"
	PlayUrl string `protobuf:"bytes,3,opt,name=PlayUrl,proto3" json:"PlayUrl,omitempty"`
	// @inject_tag: json:"cover_url"
	CoverUrl string `protobuf:"bytes,4,opt,name=CoverUrl,proto3" json:"CoverUrl,omitempty"`
	// @inject_tag: json:"favorite_count"
	FavoriteCount int64 `protobuf:"varint,5,opt,name=FavoriteCount,proto3" json:"FavoriteCount,omitempty"`
	// @inject_tag: json:"comment_count"
	CommentCount int64 `protobuf:"varint,6,opt,name=CommentCount,proto3" json:"CommentCount,omitempty"`
	// @inject_tag: json:"is_favorite"
	IsFavorite bool `protobuf:"varint,7,opt,name=IsFavorite,proto3" json:"IsFavorite,omitempty"`
	// @inject_tag: json:"title"
	Title                string   `protobuf:"bytes,8,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_9124750cb8e84e11, []int{0}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Video) GetAuthor() *User {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Video) GetPlayUrl() string {
	if m != nil {
		return m.PlayUrl
	}
	return ""
}

func (m *Video) GetCoverUrl() string {
	if m != nil {
		return m.CoverUrl
	}
	return ""
}

func (m *Video) GetFavoriteCount() int64 {
	if m != nil {
		return m.FavoriteCount
	}
	return 0
}

func (m *Video) GetCommentCount() int64 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *Video) GetIsFavorite() bool {
	if m != nil {
		return m.IsFavorite
	}
	return false
}

func (m *Video) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*Video)(nil), "services.Video")
}

func init() { proto.RegisterFile("videoModels.proto", fileDescriptor_9124750cb8e84e11) }

var fileDescriptor_9124750cb8e84e11 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0xd4, 0xa4, 0xe9, 0x54, 0x8b, 0x0e, 0x1e, 0x96, 0x1e, 0x24, 0x14, 0x91, 0x9c,
	0x22, 0xe8, 0xd1, 0x93, 0xa6, 0x08, 0x39, 0x08, 0x12, 0xac, 0x07, 0x6f, 0xd5, 0x0e, 0xb8, 0xb0,
	0xed, 0xc8, 0xec, 0x66, 0xc1, 0x1f, 0xee, 0x5d, 0xba, 0x35, 0xd2, 0x9e, 0x96, 0xf7, 0xbe, 0xf7,
	0x76, 0x86, 0x81, 0xb3, 0x60, 0x56, 0xc4, 0x4f, 0xbc, 0x22, 0xeb, 0xaa, 0x2f, 0x61, 0xcf, 0x98,
	0x3b, 0x92, 0x60, 0x3e, 0xc8, 0x4d, 0x4f, 0x3b, 0x47, 0xb2, 0xcf, 0x66, 0x3f, 0x0a, 0xd2, 0xd7,
	0x6d, 0x03, 0x27, 0x90, 0x34, 0x73, 0xad, 0x0a, 0x55, 0x0e, 0xda, 0xa4, 0x99, 0xe3, 0x15, 0x64,
	0xf7, 0x9d, 0xff, 0x64, 0xd1, 0x49, 0xa1, 0xca, 0xf1, 0xcd, 0xa4, 0xea, 0xbf, 0xa9, 0x16, 0x8e,
	0xa4, 0xfd, 0xa3, 0xa8, 0x61, 0xf8, 0x6c, 0x97, 0xdf, 0x0b, 0xb1, 0x7a, 0x50, 0xa8, 0x72, 0xd4,
	0xf6, 0x12, 0xa7, 0x90, 0xd7, 0x1c, 0x48, 0xb6, 0xe8, 0x28, 0xa2, 0x7f, 0x8d, 0x97, 0x70, 0xf2,
	0xb8, 0x0c, 0x2c, 0xc6, 0x53, 0xcd, 0xdd, 0xc6, 0xeb, 0x34, 0x0e, 0x3e, 0x34, 0x71, 0x06, 0xc7,
	0x35, 0xaf, 0xd7, 0xb4, 0xf1, 0xbb, 0x50, 0x16, 0x43, 0x07, 0x1e, 0x5e, 0x00, 0x34, 0xae, 0xaf,
	0xe9, 0x61, 0xa1, 0xca, 0xbc, 0xdd, 0x73, 0xf0, 0x1c, 0xd2, 0x17, 0xe3, 0x2d, 0xe9, 0x3c, 0xae,
	0xb0, 0x13, 0x0f, 0xe3, 0xb7, 0x51, 0x75, 0x7d, 0x17, 0x6f, 0xe0, 0xde, 0xb3, 0xf8, 0xde, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x67, 0x26, 0x2b, 0x64, 0x3c, 0x01, 0x00, 0x00,
}
