// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 用户注册
type UserRegisterRequest struct {
	// @inject_tag: json:"user_name" from:"user_name" uri:"user_name"
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// @inject_tag: json:"password" from:"password" uri:"password"
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{0}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserRegisterResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	// @inject_tag: json:"status_msg"
	StatusMsg string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @inject_tag: json:"token"
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResponse) Reset()         { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()    {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{1}
}

func (m *UserRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponse.Unmarshal(m, b)
}
func (m *UserRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponse.Marshal(b, m, deterministic)
}
func (m *UserRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponse.Merge(m, src)
}
func (m *UserRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponse.Size(m)
}
func (m *UserRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponse proto.InternalMessageInfo

func (m *UserRegisterResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UserRegisterResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *UserRegisterResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserRegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 用户登录
type UserLoginRequest struct {
	// @inject_tag: json:"username" from:"username" uri:"username"
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// @inject_tag: json:"password" from:"password" uri:"password"
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{2}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	// @inject_tag: json:"status_msg"
	StatusMsg string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @inject_tag: json:"token"
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{3}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UserLoginResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *UserLoginResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 用户信息
type UserRequest struct {
	// @inject_tag: json:"user_id" from:"user_id" uri:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @inject_tag: json:"token" from:"token" uri:"token"
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{4}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	// @inject_tag: json:"status_msg"
	StatusMsg string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// @inject_tag: json:"user"
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{5}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *UserResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// 关注，粉丝
// 关注，取消关注
type RelationActionRequest struct {
	// @inject_tag: json:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @inject_tag: json:"token"
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// @inject_tag: json:"to_user_id"
	ToUserId int64 `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	// @inject_tag: json:"action_type"
	ActionType           int32    `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationActionRequest) Reset()         { *m = RelationActionRequest{} }
func (m *RelationActionRequest) String() string { return proto.CompactTextString(m) }
func (*RelationActionRequest) ProtoMessage()    {}
func (*RelationActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{6}
}

func (m *RelationActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationActionRequest.Unmarshal(m, b)
}
func (m *RelationActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationActionRequest.Marshal(b, m, deterministic)
}
func (m *RelationActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationActionRequest.Merge(m, src)
}
func (m *RelationActionRequest) XXX_Size() int {
	return xxx_messageInfo_RelationActionRequest.Size(m)
}
func (m *RelationActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RelationActionRequest proto.InternalMessageInfo

func (m *RelationActionRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RelationActionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RelationActionRequest) GetToUserId() int64 {
	if m != nil {
		return m.ToUserId
	}
	return 0
}

func (m *RelationActionRequest) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type RelationActionResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	// @inject_tag: json:"status_msg"
	StatusMsg            string   `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationActionResponse) Reset()         { *m = RelationActionResponse{} }
func (m *RelationActionResponse) String() string { return proto.CompactTextString(m) }
func (*RelationActionResponse) ProtoMessage()    {}
func (*RelationActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{7}
}

func (m *RelationActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationActionResponse.Unmarshal(m, b)
}
func (m *RelationActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationActionResponse.Marshal(b, m, deterministic)
}
func (m *RelationActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationActionResponse.Merge(m, src)
}
func (m *RelationActionResponse) XXX_Size() int {
	return xxx_messageInfo_RelationActionResponse.Size(m)
}
func (m *RelationActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RelationActionResponse proto.InternalMessageInfo

func (m *RelationActionResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RelationActionResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

// 关注列表
type FollowListRequest struct {
	// @inject_tag: json:"user_id" from:"user_id" uri:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @inject_tag: json:"token" from:"token" uri:"token"
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowListRequest) Reset()         { *m = FollowListRequest{} }
func (m *FollowListRequest) String() string { return proto.CompactTextString(m) }
func (*FollowListRequest) ProtoMessage()    {}
func (*FollowListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{8}
}

func (m *FollowListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowListRequest.Unmarshal(m, b)
}
func (m *FollowListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowListRequest.Marshal(b, m, deterministic)
}
func (m *FollowListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowListRequest.Merge(m, src)
}
func (m *FollowListRequest) XXX_Size() int {
	return xxx_messageInfo_FollowListRequest.Size(m)
}
func (m *FollowListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowListRequest proto.InternalMessageInfo

func (m *FollowListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FollowListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type FollowListResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	// @inject_tag: json:"status_msg"
	StatusMsg string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// @inject_tag: json:"user_list"
	UserList             []*User  `protobuf:"bytes,3,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowListResponse) Reset()         { *m = FollowListResponse{} }
func (m *FollowListResponse) String() string { return proto.CompactTextString(m) }
func (*FollowListResponse) ProtoMessage()    {}
func (*FollowListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{9}
}

func (m *FollowListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowListResponse.Unmarshal(m, b)
}
func (m *FollowListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowListResponse.Marshal(b, m, deterministic)
}
func (m *FollowListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowListResponse.Merge(m, src)
}
func (m *FollowListResponse) XXX_Size() int {
	return xxx_messageInfo_FollowListResponse.Size(m)
}
func (m *FollowListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowListResponse proto.InternalMessageInfo

func (m *FollowListResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *FollowListResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *FollowListResponse) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

// 粉丝列表
type FollowerListRequest struct {
	// @inject_tag: json:"user_id" from:"user_id" uri:"user_id"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @inject_tag: json:"token" from:"token" uri:"token"
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowerListRequest) Reset()         { *m = FollowerListRequest{} }
func (m *FollowerListRequest) String() string { return proto.CompactTextString(m) }
func (*FollowerListRequest) ProtoMessage()    {}
func (*FollowerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{10}
}

func (m *FollowerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerListRequest.Unmarshal(m, b)
}
func (m *FollowerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerListRequest.Marshal(b, m, deterministic)
}
func (m *FollowerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerListRequest.Merge(m, src)
}
func (m *FollowerListRequest) XXX_Size() int {
	return xxx_messageInfo_FollowerListRequest.Size(m)
}
func (m *FollowerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerListRequest proto.InternalMessageInfo

func (m *FollowerListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FollowerListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type FollowerListResponse struct {
	// @inject_tag: json:"status_code"
	StatusCode int32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code"`
	// @inject_tag: json:"status_msg"
	StatusMsg string `protobuf:"bytes,2,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// @inject_tag: json:"user_list"
	UserList             []*User  `protobuf:"bytes,3,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowerListResponse) Reset()         { *m = FollowerListResponse{} }
func (m *FollowerListResponse) String() string { return proto.CompactTextString(m) }
func (*FollowerListResponse) ProtoMessage()    {}
func (*FollowerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{11}
}

func (m *FollowerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowerListResponse.Unmarshal(m, b)
}
func (m *FollowerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowerListResponse.Marshal(b, m, deterministic)
}
func (m *FollowerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowerListResponse.Merge(m, src)
}
func (m *FollowerListResponse) XXX_Size() int {
	return xxx_messageInfo_FollowerListResponse.Size(m)
}
func (m *FollowerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowerListResponse proto.InternalMessageInfo

func (m *FollowerListResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *FollowerListResponse) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *FollowerListResponse) GetUserList() []*User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func init() {
	proto.RegisterType((*UserRegisterRequest)(nil), "services.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "services.UserRegisterResponse")
	proto.RegisterType((*UserLoginRequest)(nil), "services.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "services.UserLoginResponse")
	proto.RegisterType((*UserRequest)(nil), "services.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "services.UserResponse")
	proto.RegisterType((*RelationActionRequest)(nil), "services.RelationActionRequest")
	proto.RegisterType((*RelationActionResponse)(nil), "services.RelationActionResponse")
	proto.RegisterType((*FollowListRequest)(nil), "services.FollowListRequest")
	proto.RegisterType((*FollowListResponse)(nil), "services.FollowListResponse")
	proto.RegisterType((*FollowerListRequest)(nil), "services.FollowerListRequest")
	proto.RegisterType((*FollowerListResponse)(nil), "services.FollowerListResponse")
}

func init() { proto.RegisterFile("userService.proto", fileDescriptor_874b4b11a4ddc7c4) }

var fileDescriptor_874b4b11a4ddc7c4 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xeb, 0xa6, 0x38, 0xe3, 0xaa, 0x6a, 0xb6, 0x69, 0xb1, 0x4c, 0x4b, 0x22, 0x9f, 0x2a,
	0x21, 0x05, 0xa9, 0x9c, 0x10, 0x1c, 0xa0, 0x20, 0x50, 0x51, 0x73, 0x71, 0xa9, 0x84, 0xb8, 0x58,
	0x26, 0x5e, 0x22, 0x0b, 0xd7, 0x6b, 0x3c, 0x1b, 0xaa, 0x1e, 0x01, 0xf1, 0x63, 0x7c, 0x19, 0xda,
	0x9d, 0x0d, 0x5d, 0x07, 0xf7, 0x12, 0x22, 0xe5, 0x12, 0x6b, 0x76, 0xf6, 0xbd, 0x7d, 0x33, 0xfb,
	0x76, 0x02, 0xbd, 0x19, 0xf2, 0xfa, 0x82, 0xd7, 0xdf, 0xf2, 0x09, 0x1f, 0x55, 0xb5, 0x90, 0x82,
	0x79, 0x48, 0x21, 0x86, 0xbb, 0x2a, 0x39, 0x16, 0x19, 0x2f, 0x90, 0x72, 0xd1, 0x18, 0xf6, 0x2e,
	0x91, 0xd7, 0x31, 0x9f, 0xe6, 0x28, 0xd5, 0xf7, 0xeb, 0x8c, 0xa3, 0x64, 0x21, 0x78, 0x6a, 0x6b,
	0x99, 0x5e, 0xf1, 0xc0, 0x19, 0x3a, 0xc7, 0xdd, 0xf8, 0x6f, 0xac, 0x72, 0x55, 0x8a, 0x78, 0x2d,
	0xea, 0x2c, 0xd8, 0xa0, 0xdc, 0x3c, 0x8e, 0x7e, 0x39, 0xd0, 0x6f, 0xf2, 0x61, 0x25, 0x4a, 0xe4,
	0x6c, 0x00, 0x3e, 0xca, 0x54, 0xce, 0x30, 0x99, 0x88, 0x8c, 0x38, 0x3b, 0x31, 0xd0, 0xd2, 0x2b,
	0x91, 0x71, 0x76, 0x04, 0x26, 0x4a, 0xae, 0x70, 0x6a, 0x78, 0xbb, 0xb4, 0x32, 0xc6, 0x29, 0xbb,
	0x0f, 0xf7, 0x94, 0x80, 0x24, 0xcf, 0x02, 0x77, 0xe8, 0x1c, 0xbb, 0xf1, 0x96, 0x0a, 0xcf, 0x32,
	0xd6, 0x87, 0x8e, 0x14, 0x5f, 0x78, 0x19, 0x6c, 0x6a, 0x08, 0x05, 0xd1, 0x3b, 0xd8, 0x55, 0x32,
	0xce, 0xc5, 0x34, 0x2f, 0xff, 0xb7, 0xa6, 0x1f, 0x0e, 0xf4, 0x2c, 0xb2, 0xf5, 0x14, 0xf4, 0x1c,
	0x7c, 0xea, 0x2b, 0xd5, 0x62, 0xa1, 0x9d, 0x76, 0xf4, 0x86, 0x8d, 0xae, 0x61, 0x9b, 0xd0, 0x2b,
	0x12, 0x1f, 0xc1, 0xa6, 0x3a, 0x4f, 0x2b, 0xf7, 0x4f, 0x76, 0x46, 0x73, 0x83, 0x8d, 0xf4, 0x29,
	0x3a, 0xa7, 0xac, 0xb0, 0x1f, 0xf3, 0x22, 0x95, 0xb9, 0x28, 0x5f, 0x4e, 0xd4, 0xef, 0x72, 0xe2,
	0xd9, 0x21, 0x80, 0x14, 0x49, 0xb3, 0x59, 0x9e, 0x14, 0x97, 0x84, 0x19, 0x80, 0x9f, 0x6a, 0xf6,
	0x44, 0xde, 0x54, 0x5c, 0x37, 0xad, 0x13, 0x03, 0x2d, 0xbd, 0xbf, 0xa9, 0x78, 0xf4, 0x01, 0x0e,
	0x16, 0x65, 0xac, 0xa6, 0x0b, 0xd1, 0x29, 0xf4, 0xde, 0x88, 0xa2, 0x10, 0xd7, 0xe7, 0x39, 0xca,
	0x25, 0x6f, 0xe6, 0xbb, 0x03, 0xcc, 0x26, 0x59, 0xd1, 0x05, 0x3d, 0x82, 0xae, 0x56, 0x51, 0xe4,
	0x28, 0x03, 0x77, 0xe8, 0xb6, 0xdc, 0x92, 0x36, 0xbf, 0x3a, 0x34, 0x7a, 0x0d, 0x7b, 0x24, 0x81,
	0xe2, 0x25, 0x2b, 0xf9, 0xe9, 0x40, 0xbf, 0x49, 0xb3, 0x86, 0x5a, 0x4e, 0x7e, 0xbb, 0xf4, 0x50,
	0xcc, 0x04, 0x64, 0x67, 0xe0, 0xcd, 0x67, 0x11, 0x3b, 0x5a, 0x40, 0x35, 0x67, 0x5e, 0xf8, 0xf0,
	0xae, 0xb4, 0xa9, 0xe3, 0x05, 0x74, 0xf4, 0x08, 0x60, 0x61, 0x73, 0xa3, 0x3d, 0x64, 0xc2, 0x07,
	0xad, 0x39, 0xc3, 0xf0, 0x14, 0x3c, 0xed, 0xda, 0xf2, 0xb3, 0x60, 0xfb, 0x8b, 0xa7, 0x11, 0xfe,
	0x60, 0x71, 0xd9, 0x40, 0x2f, 0x60, 0xa7, 0xe9, 0x62, 0x36, 0xb8, 0xdd, 0xd9, 0xfa, 0xcc, 0xc2,
	0xe1, 0xdd, 0x1b, 0x0c, 0xe9, 0x5b, 0x80, 0x5b, 0xef, 0x31, 0x4b, 0xfa, 0x3f, 0xb6, 0x0e, 0x0f,
	0xdb, 0x93, 0x86, 0x68, 0x0c, 0xdb, 0xf6, 0xd5, 0xdb, 0x9d, 0x6e, 0x71, 0x96, 0xdd, 0xe9, 0x36,
	0xc7, 0x9c, 0xfa, 0x1f, 0xbb, 0xa3, 0xc7, 0xcf, 0xf4, 0x1f, 0x14, 0x7e, 0xda, 0xd2, 0xdf, 0x27,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x78, 0x9f, 0xf8, 0xab, 0xd9, 0x06, 0x00, 0x00,
}
