// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: userservice.protos

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/protos"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protos package it is being compiled against.
// A compilation error at this line likely means your copy of the
// protos package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the protos package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	Login(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error)
	Register(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error)
	UserInfo(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error)
	RelationAction(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error)
	FollowList(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error)
	FollowerList(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Login(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Login", in)
	out := new(UserDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Register(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Register", in)
	out := new(UserDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserInfo(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UserInfo", in)
	out := new(UserDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) RelationAction(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.RelationAction", in)
	out := new(UserDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FollowList(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FollowList", in)
	out := new(UserDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FollowerList(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserDetailResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FollowerList", in)
	out := new(UserDetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Login(context.Context, *UserRequest, *UserDetailResponse) error
	Register(context.Context, *UserRequest, *UserDetailResponse) error
	UserInfo(context.Context, *UserRequest, *UserDetailResponse) error
	RelationAction(context.Context, *UserRequest, *UserDetailResponse) error
	FollowList(context.Context, *UserRequest, *UserDetailResponse) error
	FollowerList(context.Context, *UserRequest, *UserDetailResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Login(ctx context.Context, in *UserRequest, out *UserDetailResponse) error
		Register(ctx context.Context, in *UserRequest, out *UserDetailResponse) error
		UserInfo(ctx context.Context, in *UserRequest, out *UserDetailResponse) error
		RelationAction(ctx context.Context, in *UserRequest, out *UserDetailResponse) error
		FollowList(ctx context.Context, in *UserRequest, out *UserDetailResponse) error
		FollowerList(ctx context.Context, in *UserRequest, out *UserDetailResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Login(ctx context.Context, in *UserRequest, out *UserDetailResponse) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func (h *userServiceHandler) Register(ctx context.Context, in *UserRequest, out *UserDetailResponse) error {
	return h.UserServiceHandler.Register(ctx, in, out)
}

func (h *userServiceHandler) UserInfo(ctx context.Context, in *UserRequest, out *UserDetailResponse) error {
	return h.UserServiceHandler.UserInfo(ctx, in, out)
}

func (h *userServiceHandler) RelationAction(ctx context.Context, in *UserRequest, out *UserDetailResponse) error {
	return h.UserServiceHandler.RelationAction(ctx, in, out)
}

func (h *userServiceHandler) FollowList(ctx context.Context, in *UserRequest, out *UserDetailResponse) error {
	return h.UserServiceHandler.FollowList(ctx, in, out)
}

func (h *userServiceHandler) FollowerList(ctx context.Context, in *UserRequest, out *UserDetailResponse) error {
	return h.UserServiceHandler.FollowerList(ctx, in, out)
}
