// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userModels.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"follow_count"
	FollowCount int64 `protobuf:"varint,3,opt,name=follow_count,json=followCount,proto3" json:"follow_count"`
	// @inject_tag: json:"follower_count"
	FollowerCount int64 `protobuf:"varint,4,opt,name=follower_count,json=followerCount,proto3" json:"follower_count"`
	// @inject_tag: json:"is_follow"
	IsFollow             bool     `protobuf:"varint,5,opt,name=is_follow,json=isFollow,proto3" json:"is_follow"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab4681ca824f7c7a, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetFollowCount() int64 {
	if m != nil {
		return m.FollowCount
	}
	return 0
}

func (m *User) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *User) GetIsFollow() bool {
	if m != nil {
		return m.IsFollow
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "services.User")
}

func init() { proto.RegisterFile("userModels.proto", fileDescriptor_ab4681ca824f7c7a) }

var fileDescriptor_ab4681ca824f7c7a = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0xf2, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x4e,
	0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0x56, 0x9a, 0xc8, 0xc8, 0xc5, 0x12, 0x5a, 0x9c, 0x5a, 0x24,
	0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x94, 0x99, 0x22,
	0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66,
	0x0b, 0x29, 0x72, 0xf1, 0xa4, 0xe5, 0xe7, 0xe4, 0xe4, 0x97, 0xc7, 0x27, 0xe7, 0x97, 0xe6, 0x95,
	0x48, 0x30, 0x83, 0x55, 0x73, 0x43, 0xc4, 0x9c, 0x41, 0x42, 0x42, 0xaa, 0x5c, 0x7c, 0x10, 0x6e,
	0x6a, 0x11, 0x54, 0x11, 0x0b, 0x58, 0x11, 0x2f, 0x4c, 0x14, 0xa2, 0x4c, 0x9a, 0x8b, 0x33, 0xb3,
	0x38, 0x1e, 0x22, 0x26, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x11, 0xc4, 0x91, 0x59, 0xec, 0x06, 0xe6,
	0x3b, 0x71, 0x47, 0x71, 0xea, 0xe9, 0x5b, 0x83, 0x5d, 0x5a, 0x9c, 0xc4, 0x06, 0xa6, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x5a, 0x5a, 0x25, 0xc5, 0x00, 0x00, 0x00,
}
