// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: userService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	Register(ctx context.Context, in *UserRegisterRequest, opts ...client.CallOption) (*UserRegisterResponse, error)
	Login(ctx context.Context, in *UserLoginRequest, opts ...client.CallOption) (*UserLoginResponse, error)
	UserInfo(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error)
	RelationAction(ctx context.Context, in *RelationActionRequest, opts ...client.CallOption) (*RelationActionResponse, error)
	FollowList(ctx context.Context, in *FollowListRequest, opts ...client.CallOption) (*FollowListResponse, error)
	FollowerList(ctx context.Context, in *FollowerListRequest, opts ...client.CallOption) (*FollowerListResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Register(ctx context.Context, in *UserRegisterRequest, opts ...client.CallOption) (*UserRegisterResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Register", in)
	out := new(UserRegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *UserLoginRequest, opts ...client.CallOption) (*UserLoginResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Login", in)
	out := new(UserLoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserInfo(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UserInfo", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) RelationAction(ctx context.Context, in *RelationActionRequest, opts ...client.CallOption) (*RelationActionResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.RelationAction", in)
	out := new(RelationActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FollowList(ctx context.Context, in *FollowListRequest, opts ...client.CallOption) (*FollowListResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FollowList", in)
	out := new(FollowListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) FollowerList(ctx context.Context, in *FollowerListRequest, opts ...client.CallOption) (*FollowerListResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.FollowerList", in)
	out := new(FollowerListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Register(context.Context, *UserRegisterRequest, *UserRegisterResponse) error
	Login(context.Context, *UserLoginRequest, *UserLoginResponse) error
	UserInfo(context.Context, *UserRequest, *UserResponse) error
	RelationAction(context.Context, *RelationActionRequest, *RelationActionResponse) error
	FollowList(context.Context, *FollowListRequest, *FollowListResponse) error
	FollowerList(context.Context, *FollowerListRequest, *FollowerListResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Register(ctx context.Context, in *UserRegisterRequest, out *UserRegisterResponse) error
		Login(ctx context.Context, in *UserLoginRequest, out *UserLoginResponse) error
		UserInfo(ctx context.Context, in *UserRequest, out *UserResponse) error
		RelationAction(ctx context.Context, in *RelationActionRequest, out *RelationActionResponse) error
		FollowList(ctx context.Context, in *FollowListRequest, out *FollowListResponse) error
		FollowerList(ctx context.Context, in *FollowerListRequest, out *FollowerListResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Register(ctx context.Context, in *UserRegisterRequest, out *UserRegisterResponse) error {
	return h.UserServiceHandler.Register(ctx, in, out)
}

func (h *userServiceHandler) Login(ctx context.Context, in *UserLoginRequest, out *UserLoginResponse) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func (h *userServiceHandler) UserInfo(ctx context.Context, in *UserRequest, out *UserResponse) error {
	return h.UserServiceHandler.UserInfo(ctx, in, out)
}

func (h *userServiceHandler) RelationAction(ctx context.Context, in *RelationActionRequest, out *RelationActionResponse) error {
	return h.UserServiceHandler.RelationAction(ctx, in, out)
}

func (h *userServiceHandler) FollowList(ctx context.Context, in *FollowListRequest, out *FollowListResponse) error {
	return h.UserServiceHandler.FollowList(ctx, in, out)
}

func (h *userServiceHandler) FollowerList(ctx context.Context, in *FollowerListRequest, out *FollowerListResponse) error {
	return h.UserServiceHandler.FollowerList(ctx, in, out)
}
